alter table if exists public.profiles
  add column if not exists headline text,
  add column if not exists primary_categories text[] not null default '{}'::text[];

alter table if exists public.projects
  add column if not exists required_skills text[] not null default '{}'::text[],
  add column if not exists preferred_experience_level text,
  add column if not exists engagement_type text;

alter table if exists public.project_interests
  add column if not exists proposed_budget numeric,
  add column if not exists estimated_duration_days integer,
  add column if not exists relevant_skills text[] not null default '{}'::text[],
  add column if not exists match_score integer;

alter table if exists public.project_logs
  add column if not exists is_system boolean not null default false;

alter table if exists public.messages
  alter column read set default false;

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  reviewer_id uuid not null references public.users(id) on delete cascade,
  reviewee_id uuid not null references public.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists reviews_project_reviewer_unique
  on public.reviews(project_id, reviewer_id);

create index if not exists projects_required_skills_gin_idx
  on public.projects using gin (required_skills);

create index if not exists profiles_primary_categories_gin_idx
  on public.profiles using gin (primary_categories);

create index if not exists project_interests_match_score_idx
  on public.project_interests(match_score desc nulls last);

alter table public.reviews enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'reviews_select_authenticated'
  ) then
    create policy reviews_select_authenticated
      on public.reviews
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'reviews'
      and policyname = 'reviews_insert_self'
  ) then
    create policy reviews_insert_self
      on public.reviews
      for insert
      to authenticated
      with check (reviewer_id = auth.uid());
  end if;
end $$;
